{
 "title": "Demo Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Outstanding Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from jobs where document['completedAt'] is null"
    }
   ]
  },
  {
   "title": "Completed Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from jobs where document['completedAt'] is not null"
    }
   ]
  },
  {
   "title": "Outstanding Jobs by Type",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 14, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "select document['job'] as job_type, count(*) as backlog from jobs where document['completedAt'] is null group by job_type order by backlog desc"
    }
   ]
  },
  {
   "title": "Top Performers",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "select s.name, count(j.document) as jobs_completed from staff s join jobs j on s.id = j.document['completedBy'] where document['completedAt'] is not null group by s.id, s.name order by jobs_completed desc"
    }
   ]
  }
 ]
}